name: retrieve-observations

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 15-23,0-1 * * *" # Every 10 minutes during UTC day (Every 10 minutes, starting at minutes past the hour, at 02:00 PM through 11:59 PM and 12:00 AM through 01:59 AM)

jobs:
  main-job:

    name: Retrieve Observation
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Branch Name
        shell: bash
        run: |
           echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
           echo "Branch name: ${GITHUB_REF#refs/heads/}"

      - name: Get Workflow ID
        shell: bash
        run: |
          WORKFLOW_ID=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                           --header 'content-type: application/json' \
          ${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .workflow_id)
          echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
          echo "Workflow id: ${WORKFLOW_ID}"
 
      - name: Get When Workflow Last Ran
        shell: bash
        id: last_workflow
        run: |
          echo "Workflow id: ${{ env.WORKFLOW_ID }}"
          LAST_CREATED_AT=$(curl --silent --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                                    --header 'content-type: application/json' \
          "${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_ID }}/runs?per_page=1&status=completed&branch=${{ env.BRANCH_NAME }}" \
          | jq -r .workflow_runs[0].created_at)
          echo "LAST_CREATED_AT=$LAST_CREATED_AT" >> $GITHUB_OUTPUT
          echo "Previous workflow created at: ${LAST_CREATED_AT}"

      - name: Retrieve and Send Observations
        run: |
          echo "User 1:"
          echo "steps.vars.outputs.LAST_CREATED_AT: ${{ env.LAST_CREATED_AT }}"
          echo "notifications_for_user.py ${{ secrets.USERNAME_A }} ${{ secrets.NTFY_A }} ${{ env.LAST_CREATED_AT }}"
          python notifications_for_user.py ${{ secrets.USERNAME_A }} ${{ secrets.NTFY_A }} ${{ env.LAST_CREATED_AT }} 
          echo "User 2:"
          python notifications_for_user.py ${{ secrets.USERNAME_B }} ${{ secrets.NTFY_B }} ${{ env.LAST_CREATED_AT }}
