name: retrieve-observations

on:
  schedule:
    - cron: "*/10 14-23,0-1 * * *" # Every 10 minutes during UTC day (Every 10 minutes, starting at minutes past the hour, at 02:00 PM through 11:59 PM and 12:00 AM through 01:59 AM)

jobs:
  main-job:

    name: Retrieve Observation
    runs-on: ubuntu-latest
    steps:

      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Current UTC Time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH

      - name: Retrieve and Send Observations
        run: |
          python notifications_for_user.py ${{ secrets.USERNAME_A }} ${{ secrets.NTFY_A }} ${{ steps.current-time.outputs.hour }}
          python notifications_for_user.py ${{ secrets.USERNAME_B }} ${{ secrets.NTFY_B }} ${{ steps.current-time.outputs.hour }}
