name: retrieve-observations

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 15-23,0-1 * * *" # Every 10 minutes during UTC day (Every 10 minutes, starting at minutes past the hour, at 02:00 PM through 11:59 PM and 12:00 AM through 01:59 AM)

jobs:
  main-job:

    name: Retrieve Observation
    runs-on: ubuntu-latest
    steps:

      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Branch Name
        shell: bash
        run: |
           echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
           echo "Branch name: ${GITHUB_REF#refs/heads/}"

      - name: Get Workflow Id
        shell: bash
        run: |
          WORKFLOW_ID=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                           --header 'content-type: application/json' \
          ${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .workflow_id)
          echo "WORKFLOW_ID=$WORKFLOW_ID" >> $GITHUB_ENV
          echo "Workflow id: ${WORKFLOW_ID}"
 
      - name: Get Previous Build Status
        shell: bash
        id: last_completed_at
        run: |
          last_created_at=$(curl --silent --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                                    --header 'content-type: application/json' \
          "${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_ID }}/runs?per_page=1&status=completed&branch=${{ env.BRANCH_NAME }}" \
          | jq -r .workflow_runs[0].created_at)
          echo "last_created_at=$last_created_at" >> $GITHUB_OUTPUT
          echo "Previous build created at: $last_created_at"

      - name: Shell/Bash Current Time
        shell: bash
        run: |
          CURRENT_MONTH =$(date +"%m")
          CURRENT_HOUR=$(date +"%H")
          CURRENT_MINUTE=$(date +"%M")
          echo "$CURRENT_MONTH"
          echo "$CURRENT_HOUR"
          echo "$CURRENT_MINUTE"

      - name: Get Current UTC Time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH

      - name: Retrieve and Send Observations
        run: |
          echo "User 1:"
          python notifications_for_user.py ${{ secrets.USERNAME_A }} ${{ secrets.NTFY_A }} ${{ steps.current-time.outputs.month }} ${{ steps.current-time.outputs.hour }} ${{ steps.current-time.outputs.minute }}
          echo "User 2:"
          python notifications_for_user.py ${{ secrets.USERNAME_B }} ${{ secrets.NTFY_B }} ${{ steps.current-time.outputs.month }} ${{ steps.current-time.outputs.hour }} ${{ steps.current-time.outputs.minute }}
