name: retrieve-observations

on:
  schedule:
    - cron: "*/10 * * * *" # run every 10th minute

jobs:
  main-job:

    name: Retrieve Observation
    runs-on: ubuntu-latest
    steps:

      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
        run: |
          echo ${{ steps.current-time.outputs.hour }}

      - name: Retrieve and Send Observations
        run: |
          python notifications_for_user.py ${{ secrets.USERNAME_A }} ${{ secrets.NTFY_A }}
          python notifications_for_user.py ${{ secrets.USERNAME_B }} ${{ secrets.NTFY_B }}
